### ISSUE TITLE
What is the encoding of metadata packet payload

### ISSUE THREAD

**Issue by brendann993** [rebelvg/node-flv#6]
This might seem like a stupid question/issue but I have been unable to convert a metadata packet payload to a readable format. It appears to just be a buffer which from what I know I should be able to buffer.toString() which returns a string but with several characters incorrect. e.g.

```
flvStream.on('flv-packet-metadata', (flvPacket) => {
    console.log(flvPacket.payload.toString())
    flvPacket.build();
});
```
results in 
```
videodatarateon║width@�@═height@�`
videocodecid@
Lavf59.16.10filesizeder╗
```
I've tried utf8 & binary encoding with the same result

I am also wondering if its possible to also add an additional metadata payload to the stream and it there is any examples of doing so

**Comment by rebelvg** [comment]
is it possible for you to share this flv file with me so I can take a look?
it's possible there's something wrong with metadata parsing
when I developed this I tried it with a lot of different files but maybe I missed something

**Comment by brendann993** [comment]
Here's a 10 second sample file. Its from a CCTV camera that streams mp4 via RTSP. Im using FFMPEG to convert to flv which is then the input. Reading the file directly from a stdout of the ffmpeg process or file results in the same as above
[10secsample.zip](https://github.com/rebelvg/node-flv/files/8381025/10secsample.zip)

**Comment by brendann993** [comment]
I also just downloaded a sample flv from https://filesamples.com/formats/flv which also gives similar results

**Comment by brendann993** [comment]
@rebelvg You can disregard this. I was not using parsePayload()
I was looking through the source and realised it was there and I completely missed it.
Its not mentioned in the readme and I had assumed the payload was being automatically parsed

**Comment by rebelvg** [comment]
Hey, great that you found the solution, I will update the docs.
